package com.sugarcrm.test.users;

import org.junit.Test;
import com.sugarcrm.candybean.datasource.FieldSet;
import com.sugarcrm.sugar.VoodooControl;
import com.sugarcrm.sugar.VoodooUtils;
import com.sugarcrm.test.SugarTest;

public class Users_24731 extends SugarTest {
	FieldSet customData = new FieldSet();
	VoodooControl employeeCtrl;

	public void setup() throws Exception {
		customData = testData.get(testName).get(0);
		sugar().login();
	}

	/**
	 * Verify Detail View of user is displayed correctly that is generated by creating employee.
	 * @throws Exception
	 */
	@Test
	public void Users_24731_execute() throws Exception {
		VoodooUtils.voodoo.log.info("Running " + testName + "...");

		// Navigate Profile Dropdown -> Employee -> Create Employee record
		// TODO: VOOD-1041
		sugar().navbar.toggleUserActionsMenu();
		employeeCtrl= new VoodooControl("a", "css", "li.profileactions-employees a");
		employeeCtrl.click();
		VoodooUtils.waitForReady();
		new VoodooControl("i", "css", "li[data-module='Employees'] i.fa-caret-down").click();
		new VoodooControl("a", "css", "li[data-module='Employees'] a[data-navbar-menu-item='LNK_NEW_EMPLOYEE']").click();
		VoodooUtils.focusFrame("bwc-frame");
		new VoodooControl("input", "id", "last_name").set(customData.get("last_name"));
		new VoodooControl("input", "id", "first_name").set(customData.get("first_name"));
		new VoodooControl("input", "id", "department").set(customData.get("department"));
		new VoodooControl("input", "id", "Users0emailAddress0").set(customData.get("email_address"));
		new VoodooControl("input", "id", "SAVE_HEADER").click();
		VoodooUtils.waitForReady();
		VoodooUtils.focusDefault();

		// Navigate to Users List View
		sugar().users.navToListView();
		VoodooUtils.focusFrame("bwc-frame");

		// Search for the user created above
		sugar().users.listView.getControl("nameBasic").set(customData.get("last_name"));
		VoodooUtils.focusDefault();
		sugar().users.listView.submitSearchForm();
		VoodooUtils.focusFrame("bwc-frame");

		// Verify one new user is created
		String fullName = String.format("%s %s", customData.get("first_name"),customData.get("last_name"));
		sugar().users.listView.getControl("firstRecordListView").assertEquals(fullName, true);
		VoodooUtils.focusDefault();

		// Click on the UserRecord
		sugar().users.listView.clickRecord(1);

		// Click Edit Button
		sugar().users.detailView.edit();

		// Click Cancel Button
		sugar().users.editView.cancel();

		// Verify no Error is displayed and record view is displayed correctly
		sugar().alerts.getError().assertVisible(false);
		VoodooUtils.focusFrame("bwc-frame");
		sugar().users.detailView.getDetailField("fullName").assertContains(fullName, true);
		VoodooUtils.focusDefault();

		VoodooUtils.voodoo.log.info(testName + " complete.");
	}

	public void cleanup() throws Exception {}
}